const SvgIcon = {
  ADD: "add",
  VIDEO: "video",
  SEARCH: "search",
  LIST: "list",
  BARS: "bars",
  ANGLE_RIGHT: "angleRight",
  ANGLE_LEFT: "angleLeft",
  BOOKMARK_OUTLINED: "bookmarkOutlined",
  BOOKMARK_FILLED: "bookmarkFilled",
  MONEY: "money",
  HISTORY: "history",
  CLOCK: "clock",
  CANCEL: "cancel",
  MOVIE: "movie",
  AUTHENTICATE: "authenticate",
  MENU: "menu",
  VISIBLE: "visible",
  INVISIBLE: "invisible",
  ERROR: "error",
  WARNING: "warning",
  SUCCESS: "success",
  INFO: "info",
  CANCEL_FILLED: "cancelFilled",
  LOGOUT: "logout",
};

export default SvgIcon;
